---

#handlers usually contains the service commands (start, stop, reload etc.)

# In case services need to be restarted after changing the locales
- name: restart dependent services
  service: name={{ item }} state=restarted
  with_items: dependent_services
